### ISSUE TITLE
Some quetions about the project

### ISSUE THREAD

**Issue by harrywang725** [xiaomengyc/I2C#1]
It seems that there are some files not provided in  your project  
1、Could you release the whole project ，or  train_frame_crsimg_center_feat.py 
2、 In the train_frame.py ,  you used  my_optim.reduce_lr . Is your my_optim.py the same as it in other wsol project?
3、How can you train your model in CUB dataset ,  In your train.sh , the setting is --train_list='../datalist/CUB/train_list.txt' , label in it is not one-hot format， but your dataset file  mydataset_crising.py   satisfy the one-hot format gt ， is there something wrong in my thoughts?
Need your reply~

**Comment by xiaomengyc** [comment]
Hi @harrywang725 ,
Sorry for the late reply.
1. `train_frame_crsimg_center_feat.py` is the same file to `train_frame.py` in `exper`.  
2.  Yes, I use a pretty simple SGD policy on all my WSOL project. In this project, I reduce the `lr` by 10x at epoch 2,3,4 (start from 0).
3.  This project does not use a one-hot format for input. The input formats for Imagenet and CUB are the same. I don't clean the one-hot format input because maybe someone needs it for multi-category projects.
